###
GET http://localhost:3000/api/cliente HTTP/1.1

###
GET http://localhost:3000/api/contar HTTP/1.1

###
GET http://localhost:3000/api/cliente/5 HTTP/1.1

###
POST http://localhost:3000/api/cliente HTTP/1.1
Content-Type: application/json

{
    "Nombres": "Felipe",
    "Apellidos": "Mendoza",
    "Email": "felipe@cecar.edu.co",
    "Telefono": "678365732"
}

###
DELETE http://localhost:3000/api/cliente/7 HTTP/1.1

###
PUT http://localhost:3000/api/cliente/5 HTTP/1.1
Content-Type: application/json

{
    "Nombres": "Mariaq",
    "Apellidos": "Perez",
    "Email": "maria@cecar.edu.co",
    "Telefono": "7693641823"
}